[supervisord]
nodaemon=true
user=root
logfile=/dev/stdout
logfile_maxbytes=0

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:gateway]
command=uvicorn app.main:app --host 127.0.0.1 --port 8000
directory=/app/services/gateway
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:auth]
command=uvicorn app.main:app --host 127.0.0.1 --port 8001
directory=/app/services/auth-service
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:patient]
command=uvicorn app.main:app --host 127.0.0.1 --port 8002
directory=/app/services/patient-service
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:doctor]
command=uvicorn app.main:app --host 127.0.0.1 --port 8003
directory=/app/services/doctor-service
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:appointment]
command=uvicorn app.main:app --host 127.0.0.1 --port 8004
directory=/app/services/appointment-service
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:telemedicine]
command=uvicorn app.main:app --host 127.0.0.1 --port 8005
directory=/app/services/telemedicine-service
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:payment]
command=uvicorn app.main:app --host 127.0.0.1 --port 8006
directory=/app/services/payment-service
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:notification]
command=uvicorn app.main:app --host 127.0.0.1 --port 8007
directory=/app/services/notification-service
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:ai-symptom]
command=uvicorn app.main:app --host 127.0.0.1 --port 8008
directory=/app/services/ai-symptom-service
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
